install rpm with yum
Signed-off-by: Artur Troian <troian.ap@gmail.com>

diff --git a/sbin/installer b/sbin/installer
--- a/sbin/installer
+++ b/sbin/installer
@@ -7,10 +7,13 @@
 # * @Copyright: (c) 2019
 #********************************************
 
-set -eu
-set -o pipefail
+# fail if command return is no 0
+set -e
 
-cagent_version="1.0.3"
+# fail if dereferencing variable is not set
+set -u
+
+set -o pipefail
 
 die () {
     echo "$@" 1>&2;
@@ -56,38 +59,43 @@ do_install () {
     case "$OS_PKGTYPE" in
         rpm)
             CAGENT_HUB_URL=$1 CAGENT_HUB_USER=$2 CAGENT_HUB_PASSWORD=$3 \
-            rpm -i "https://drive.google.com/uc?export=download&id=1h6Y9lmqg4r5qvyrmvY6rbvhzNCnoyODc"
-#            rpm -i "https://github.com/cloudradar-monitoring/cagent/releases/download/${cagent_version}/cagent_${cagent_version}_linux_${arch_type}.rpm"
+            yum install  "https://drive.google.com/uc?export=download&id=1h6Y9lmqg4r5qvyrmvY6rbvhzNCnoyODc" -y
+#            rpm -i "https://github.com/cloudradar-monitoring/cagent/releases/download/$1/cagent_$1_linux_${arch_type}.rpm"
         ;;
         deb)
-#        && wget -O "$TEMP_DEB" "https://github.com/cloudradar-monitoring/cagent/releases/download/${cagent_version}/cagent_${cagent_version}_linux_${arch_type}.deb" \
-            TEMP_DEB="$(mktemp)" \
-            && wget --no-check-certificate -O "$TEMP_DEB" "https://drive.google.com/uc?export=download&id=1V8hr0O3BsGZkXnxNlTGDPNTBuEc9M_qy" \
-            && CAGENT_HUB_URL=$1 CAGENT_HUB_USER=$2 CAGENT_HUB_PASSWORD=$3 dpkg -i "$TEMP_DEB" \
-            && rm -f "$TEMP_DEB"
+#        && wget -O "$TEMP_DEB" "https://github.com/cloudradar-monitoring/cagent/releases/download/$1/cagent_$1_linux_${arch_type}.deb" \
+            TEMP_DEB="$(mktemp cagent.XXXXXXXXXX.deb)" \
+            && wget --no-check-certificate -O ${TEMP_DEB} "https://drive.google.com/uc?export=download&id=1V8hr0O3BsGZkXnxNlTGDPNTBuEc9M_qy" \
+            && CAGENT_HUB_URL=$2 CAGENT_HUB_USER=$3 CAGENT_HUB_PASSWORD=$4 dpkg -i ${TEMP_DEB} \
+            && rm -f ${TEMP_DEB} \
+            && touch /etc/init/cagent.conf
         ;;
     esac
 }
 
 do_uninstall () {
+    set +e
     case "$OS_PKGTYPE" in
         rpm)
-            rpm -e cagent
+            yum remove cagent -y
         ;;
         deb)
-            dpkg -P cagent
+            apt-get remove --purge cagent -y
         ;;
     esac
+
+    rm -rf /etc/cagent
+    rm -rf /var/log/cagent/
 }
 
 if [[ "${1:-}" = "uninstall" ]]; then
     do_uninstall
 elif [[ "${1:-}" = "install" ]]; then
-    if [[ $# -ne 4 ]]; then
+    if [[ $# -ne 5 ]]; then
         die "not enough arguments"
     fi
 
-    do_install $2 $3 $4
+    do_install $2 $3 $4 $5
 elif [[ "${1:-}" = "check" ]] ; then
     if [[ "${2:-}" = "installed" ]] ; then
         do_check_install
